name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.11.0
      - run: npm install
      - run: npm test
  code-ql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.11.0
      - run: npm install
      - uses: github/codeql-action/init@master
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@master